title: Orbit Lab, SIT, Bhubaneswar, India 
description: Orbit Lab is an SiliconTech initiative to develop a satellite technology using the nano-satellite format PocketQube.

theme: null

  
language: en
direction: auto

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
